[pytest]
asyncio_mode = auto
addopts = --import-mode=importlib
consider_namespace_packages = true
testpaths = packages/core/tests services/proxy/tests services/api/tests
filterwarnings =
    ignore::DeprecationWarning
